export const styles = {
  container: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",  // Center vertically
    alignItems: "center",      // Center horizontally
    height: "100vh", // Full viewport height
    margin: "0",
    fontFamily: "Arial, sans-serif",
    backgroundColor: "#f4f4f9",
  },
  header: {
    textAlign: "center",
    color: "#333",
    margin: "20px 0",
  },
  chatBox: {
    flex: 1,
    width: "100%",
    maxWidth: "800px", // Max width for the chat box
    overflowY: "auto",
    backgroundColor: "#ffffff",
    borderRadius: "8px",
    padding: "15px",
    boxShadow: "inset 0 2px 4px rgba(0, 0, 0, 0.05)",
    marginBottom: "20px",
    lineHeight: "1.6",
    alignItems: 'center',
    justifyContent: 'center',
    },
  userMessage: {
    textAlign: "right",
    margin: "10px 0",
    padding: "10px",
    backgroundColor: "#0084ff",
    color: "#ffffff",
    borderRadius: "20px",
    maxWidth: "80%",
    alignSelf: "flex-end",
    wordBreak: "break-word",
    alignItems: 'center',
    justifyContent: 'center',
  },
  botMessage: {
    textAlign: "left",
    margin: "10px 0",
    padding: "10px",
    backgroundColor: "#e1e5eb",
    color: "#333",
    borderRadius: "20px",
    maxWidth: "80%",
    alignSelf: "flex-start",
    wordBreak: "break-word",
    alignItems: 'center',
    justifyContent: 'center',
  },
  loading: {
    textAlign: "center",
    color: "#666",
  },
  inputContainer: {
    display: "flex",
    alignItems: "center",
    backgroundColor: "#fff",
    borderRadius: "30px",
    boxShadow: "0 2px 4px rgba(0, 0, 0, 0.1)",
    padding: "5px",
    width: "100%",
    maxWidth: "800px", // Match max width of chatBox for uniformity
    
  },
  input: {
    flex: 1,
    border: "solid #ccc",
    marginBottom: '10px',
    padding: "10px",
    borderRadius: "5px",
    outline: "none",
    // minHeight: "60px", // Make textarea taller
    resize: "none", // Disable resizing
    alignItems: 'center',
    justifyContent: 'center',
  },
  sendButton: {
    backgroundColor: "#0084ff",
    color: "#ffffff",
    border: "none",
    padding: "10px 15px",
    borderRadius: "50%",
    cursor: "pointer",
    marginLeft: "5px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    transition: "background-color 0.3s ease",
  },
  sendButtonHover: {
    backgroundColor: "#0056b3",
  },
  form: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    maxWidth: '400px', // Slightly wider form for better usability
    padding: '30px',
    borderRadius: '8px',
    backgroundColor: '#ffffff',
    boxShadow: '0 4px 8px rgba(0, 0, 0, 0.1)',
    marginTop: '20px',
  },
  button: {
    padding: '12px 20px',
    backgroundColor: '#007bff',
    color: '#ffffff',
    border: 'none',
    borderRadius: '5px',
    cursor: 'pointer',
    fontSize: '16px',
    marginTop: '15px',
    transition: 'background-color 0.3s ease',
  },
  buttonHover: {
    backgroundColor: '#0056b3',
  },
  switchText: {
    marginTop: '20px',
    textAlign: 'center',
    fontSize: '14px',
    color: '#333',
  },
  switchLink: {
    color: '#007bff',
    cursor: 'pointer',
    textDecoration: 'none',
    marginLeft: '5px',
    transition: 'color 0.3s ease',
  },
  switchLinkHover: {
    color: '#0056b3',
  },
  logoutButton: {
    position: 'absolute',
    top: '20px',
    right: '20px',
    padding: '8px 15px',
    backgroundColor: '#dc3545',
    color: '#ffffff',
    border: 'none',
    borderRadius: '5px',
    cursor: 'pointer',
    fontSize: '14px',
    transition: 'background-color 0.3s ease',
  },
  logoutButtonHover: {
    backgroundColor: '#a71d2a',
  },
  pageContainer: {
    display: 'flex',
    height: '100vh',
  },
  sidebar: {
    width: '250px',
    borderRight: '1px solid #ccc',
    padding: '20px',
    overflowY: 'auto',
  },
  chatContainer: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
  },
  newConversationButton: {
    width: '100%',
    padding: '10px',
    marginBottom: '20px',
    backgroundColor: '#4CAF50',
    color: 'white',
    border: 'none',
    borderRadius: '5px',
    cursor: 'pointer',
  },
  conversationItem: {
    padding: '10px',
    cursor: 'pointer',
    borderRadius: '5px',
    marginBottom: '5px',
    alignItems: 'center',
  },
  playButton: {
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    marginLeft: '10px',
    color: '#4a4a4a',
  },
};
